### PR TITLE
bugfix/#43 - template for haproxy_listen

### PR DESCRIPTION
**Pull request by SydOps**
- Align
- keyword 'http-send-name-header' and 'http-check-except'
- Sample for bind in haproxy_listen
- add extra part for any options which are not included, currently only for global, default and listens.

### CODE REVIEW

**Comment by PierrePaul** [comment]
Attaching issue #43 to this pull request. Will try to test it today.

**Comment by SydOps** [comment]
Finally I have to add the last extra part to make it work for my project directly. 

I am fine to access my fork currently and happy to switch to this main repo, when it is merged. 
```
+{% if item.extra is defined %}
 +{% for parameter in item.extra %}
 +    {{ parameter }}
 +{% endfor %}
 +{% endif -%}
```

If this is merged, and you agree this idea,  I will implement the new part of `resolvers.cfg` with ticket #46

**Comment by pbuyle** [comment]
Sorry for the delay and lack of actions. We are finding that we are not using this role anymore and cannot commit to its maintenance. We are looking for an individual or organization to take over. Please see #53 if you are interested.

**Comment by benwebber** [comment]
Hey Bill,

Let's rethink how to support flexible configuration stanzas as part of 2x. I will be opening an RFC soon  (this week) and would appreciate your comments.

Cheers!

**Pull request closed without merging**
